Nombre = input("ingrese el nombre: ")
Edad = input("ingrese la edad: ")
Altura = input("ingrese la altura: ")
Tipo_de_sangre = input("ingrese el tipo de sangre: ")
Informacion_Personal = tuple((Nombre, Edad, Altura,Tipo_de_sangre ))
print(Informacion_Personal)

Pais = input("ingrese el pais: ")
Ciudad = input("ingrese la cuidad: ")
Direccion = input("ingrese la direccion: ")
Informacion_De_Direccion = tuple((Pais, Ciudad, Direccion ))
print(Informacion_De_Direccion)

Posee_Diploma = input("Usted posee un diploma? ")
Tutulo_Universitario = input("Usted tiene algun titulo universitario? ")
CUrsos_Extras = input("Tiene algun curso extra? ")
Posee_Maestria = input("Posee alguna maestria? ")
Informacion_De_Educacion = tuple((Posee_Diploma, Tutulo_Universitario, CUrsos_Extras, Posee_Maestria ))
print(Informacion_De_Educacion)

Experiencia_Laboral = input("Posee experiencia laboral? ")
input("si no posee experiecia laboral, colocar NO en los siguientes puntos")
Años_De_experiencia = input("Cuantos años de experiencia tiene? ")
Tipo_De_Experiencia = input("Que tipo de experiencia tiene? ")
Lugar = input("Lugar en donde obtubo la experiencia: ")
Informacion_Laboral = tuple((Experiencia_Laboral, Años_De_experiencia,Tipo_De_Experiencia, Lugar ))
print(Informacion_Laboral)
